export const HOME_COPY = {
  en: {
    modify: 'Modify information',
    theme: 'change theme',
    gallery: 'image gallery',
    settings: 'Settings',
    uploadAvatar: 'Upload avatar',
    back: 'Back',
  userName: 'User name',
  account: 'Account',
  idUnique: 'Unique ID',
  loginPassword: 'Login password',
  inviteCode: 'Invite code',
  inviteOnly: 'Registration is currently limited to invited testers',
  passwordManaged: 'Password is protected by Supabase Auth',
  passwordNotViewable: 'Saved passwords cannot be viewed. You can change it with your current password.',
  changePassword: 'Change password',
  currentPassword: 'Current password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  savePassword: 'Save password',
  changingPassword: 'Changing...',
  passwordChanged: 'Password changed',
  passwordMismatch: 'The new passwords do not match',
  currentPasswordWrong: 'Current password is incorrect',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  accountAccess: 'Account access',
  uploadPhotoLocation: 'Create star from photo GPS',
  photoLocationLoading: 'Reading photo location...',
  photoLocationCreated: 'Star created from photo',
  photoLocationNoGps: 'This photo has no usable GPS',
  photoLocationFailed: 'Could not read this photo',
  photoGpsNoteTitle: 'Photo location',
  restoreTrackDraft: 'An unsaved route draft was found. Restore it?',
  routeGpsWeak: 'GPS signal is weak. Waiting for a stable position.',
    loginTitle: 'Account login',
    registerTitle: 'Account registration',
    loginHint: 'Enter your registered ID and password to log in.',
    registerHint: 'Create a unique ID first, then use it on any device.',
    login: 'Log in',
    register: 'Register',
    loggingIn: 'Logging in...',
    registering: 'Creating...',
    restoringSession: 'Restoring your session...',
    registerPassword: 'Set password',
    registerSuccess: 'Registration complete. Please log in.',
    loginMissing: 'Enter an account and password',
    registerMissing: 'Set an account and password',
  passwordTooShort: 'Password must be at least 6 characters',
    loginError: 'Account does not exist or password is incorrect',
    registerError: 'Could not register this account',
    accountExists: 'This account already exists',
    cloudSetupRequired: 'Cloud service is temporarily unavailable. Please try again later.',
    cloudConnectivityIssue: 'Cloud connection failed. Please check the network, or open this page in Safari/Chrome.',
    cloudProjectMismatch: 'Login status is invalid. Please sign in again.',
    cloudConfigInvalid: 'Cloud service is temporarily unavailable. Please try again later.',
    cloudEmailConfirmRequired: 'Disable Supabase email confirmation first',
    noImages: 'No uploaded images yet',
    openPermissions: 'Open permissions',
    openPermissionsHint: 'Request location',
    userManual: 'User manual',
    openManual: 'Open manual',
    closeManual: 'Close manual',
    exportData: 'Export data',
    exportJson: 'Export report',
    exportingData: 'Exporting...',
    exportPreparing: 'Preparing export',
    exportImagesProgress: 'Processing images {completed}/{total}',
    exportGenerating: 'Generating file',
    exportImagesMissing: 'Export complete. {count} images were not embedded.',
    exportDataReady: 'Report exported',
    exportDataPartial: 'Report exported. Some images could not be embedded.',
    exportDataFailed: 'Could not export data',
    mcpAccess: 'Get MCP',
    mcpGenerateToken: 'Generate MCP token',
    mcpGenerating: 'Generating...',
    mcpTokenReady: 'Token generated. Copy it now.',
    mcpCopyEndpoint: 'Copy endpoint',
    mcpCopyHeader: 'Copy header value',
    mcpCopied: 'Copied',
    mcpRevoke: 'Revoke',
    mcpNoTokens: 'No active MCP tokens',
    mcpNameLabel: 'Name',
    mcpNameValue: 'My Life Memory',
    mcpTransportLabel: 'Transport type',
    mcpTransportValue: 'Streamable HTTP',
    mcpEndpoint: 'Server address',
    mcpCustomHeader: 'Custom request header',
    mcpHeaderName: 'Authorization',
    mcpHeaderValueHint: 'Generate a token first',
    mcpTokenPrefix: 'Active token',
    mcpFailed: 'MCP service unavailable',
    mcpRevoked: 'Token revoked',
    mcpTokenWarning: 'The full token is shown only once.',
    apiSecurity: 'API & security',
    apiMemoryApiTitle: 'Memory API',
    apiMemoryApiBody: 'Memory API is a Supabase Edge Function for authenticated integrations. It reads the current user memory data and requires a real user access token.',
    apiMcpSecurityTitle: 'MCP access',
    apiMcpSecurityBody: 'Cloud MCP is also a Supabase Edge Function. It verifies the generated MCP token, maps it to one user, and exposes read-only tools to AI clients.',
    apiTokenSecurityTitle: 'Token generation',
    apiTokenSecurityBody: 'The MCP token is generated on Supabase, not in frontend code. The full token is shown once; Supabase stores only a SHA-256 hash and a short prefix.',
    apiStorageSecurityTitle: 'Private media',
    apiStorageSecurityBody: 'Images are stored in the private life-media bucket under each user ID. The database keeps paths and metadata instead of public image files.',
    apiDirectApiTitle: 'Direct API shape',
    apiDirectApiBody: 'External tools should POST to memory-api with Authorization: Bearer <user access token>, apikey: <publishable key>, and an action such as search_memories.',
    apiNeverExposeTitle: 'Do not expose',
    apiNeverExposeBody: 'Never put service_role, invite codes, real session tokens, raw MCP tokens, or database connection strings into the app page, README examples, exports, or screenshots.',
    searchResultsTitle: 'Search results',
    searchResultsFor: 'for',
    noSearchResults: 'No matching notes',
    initialPermissionsTitle: 'Location permission',
    initialPermissionsBody: 'Allow location to center the map on your current position and update the origin marker.',
    notNow: 'Later',
    manualIntro: 'My life memory is a private life map. It starts from your current location, lets you place stars for meaningful places, and connects notes, photos, movement routes, coordinates, and statistics into one personal memory space.',
    manualSections: [
      { title: 'Map and stars', body: 'A star is one place memory. Tap an empty spot on the map to place a star directly, or drag the star tool onto the map to create it more deliberately. After a star is placed, you can still drag it to adjust the location. Tap a star to write notes, add photos, view coordinates, copy them, or choose another map app to open the place.' },
      { title: 'Location and direction', body: 'Open permissions to request real GPS and device direction. The black origin marker is your current position, and the translucent probe shows the phone-facing direction. On mobile Safari, direction data usually requires HTTPS and a user tap. Walking updates depend on GPS accuracy, so outdoor movement is more reliable than indoor testing.' },
      { title: 'Records', body: 'Notes are created from stars. The note time is based on the first creation time and should not be edited later. In My records, newer notes appear above older ones. Open a note to edit text and images directly, then use the save button in the expanded tools. The calendar shows dots only on days that have saved content or star marks.' },
      { title: 'Statistics', body: 'Trip statistics summarize stars, routes, frequent locations, rankings, and the dotted world map. Bar chart colors follow star colors, so the statistics stay visually connected to the memories on the map. The dotted world map is a decorative overview and can be opened for a fuller browsing experience.' },
      { title: 'Account and sync', body: 'Each ID is unique. Register first, then log in with that ID and password. After login, stars, notes, routes, settings, and profile data sync to the cloud. Different accounts stay separated even on the same device, so switching accounts should show each user’s own data.' },
    ],
    manualIconsTitle: 'Common icons',
    manualIconMap: 'Map opens the main map, where your current location, stars, routes, and map style controls live.',
    manualIconStats: 'Stats opens distance, star, location ranking, and dotted world-map summaries.',
    manualIconRecords: 'Records opens your saved notes in timeline form; use filters, search, and calendar to find them.',
    manualIconHome: 'Home contains profile editing, theme colors, image gallery, permissions, this manual, and account exit.',
    manualIconStar: 'Star creates a place memory. You can tap the map to place it, drag the star tool onto the map, tap an existing star to edit it, and drag a placed star to refine its location.',
    manualIconLocation: 'Location returns the map to your current GPS origin. The direction probe rotates with phone orientation when browser permission and hardware support are available.',
    manualIconRoute: 'Route starts, pauses, saves, or reviews an adaptive movement record. It uses one GPS filter for walking, cycling, driving, and transit; distance depends on GPS accuracy and updates while location points arrive. Indoor, elevator, and underground GPS can drift; for a cleaner route, pause before entering and resume after leaving.',
    manualIconCamera: 'Camera opens photo capture or image selection for a note; on mobile it can use the full-screen camera flow when the browser allows it.',
    manualIconPhotoGps: 'The star upload icon, drawn as a star with an upload arrow, reads GPS from one original photo and creates a star with a photo note at that location. If the photo has no usable location data, it only shows a short notice and does not create a star.',
    manualIconSave: 'Save writes the current note edits, including text, images, color, and font-size changes.',
    manualIconCopy: 'Copy places coordinates or other selected information on the clipboard and shows a short copied message.',
    manualIconShare: 'Open map lets you choose Apple, AMap, Baidu, or Google Maps when supported by the device.',
    manualIconSearch: 'Search finds notes, place text, or coordinates without moving through every star manually.',
    permissionRequesting: 'Requesting permissions...',
    permissionReady: 'Permissions requested',
    permissionDenied: 'Could not open permissions. Check browser site settings.',
    permissionUnsupported: 'Browser permissions are unavailable',
    language: 'Language',
    exit: 'Exit Account',
    base: 'Page background',
    card: 'Cards & panels',
    icon: 'Buttons & icons',
    dark: 'Selected accent',
    recordsTitle: 'My records',
    recordsMenu: 'Records menu',
    allRecords: 'All',
    monthlyRecords: 'Monthly',
    annualRecords: 'Annual',
    noRecords: 'No note records yet',
    calendar: 'Calendar',
    closeCalendar: 'Close calendar',
    clearDateFilter: 'Clear date filter',
    previousCalendarPage: 'Previous calendar page',
    nextCalendarPage: 'Next calendar page',
    weekdays: ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'],
    search: 'Search',
    searchRecords: 'Search records',
    searchPlaceholder: 'Quickly search for places and text...',
    runSearch: 'Run search',
    backToRecords: 'Back to records',
    readerMissing: 'This record is no longer available',
    readerEdit: 'Save record',
    readerReadingSize: 'Change reading size',
    readerUnderline: 'Underline text',
    readerAddPhoto: 'Add photo',
    readerJumpImage: 'Add image',
    readerEditColor: 'Edit color',
    readerCollapseTools: 'Collapse reading tools',
    readerExpandTools: 'Expand reading tools',
    readerLocate: 'Locate record on map',
    removeImage: 'Remove image',
    bottomMap: 'Map',
    bottomStats: 'Stats',
    bottomNotes: 'Notes',
    bottomHome: 'Home',
    untitledNote: 'Untitled note',
    noteLabel: 'Note',
    starLabel: 'Star',
    addStar: 'Add star',
    noteImageAlt: 'Note attachment',
    userFallback: 'User',
    userAvatarAlt: 'User avatar',
    currentMapStyleAlt: 'Current map style',
    aerialMapAlt: 'Aerial',
    darkMapAlt: 'Dark',
    lightMapAlt: 'Light',
    closeImagePreview: 'Close image preview',
    downloadImage: 'Download image',
  },
  zh: {
    modify: '修改信息',
    theme: '更换主题',
    gallery: '图片仓库',
    settings: '设置',
    uploadAvatar: '上传头像',
    back: '返回',
  userName: '用户姓名',
  account: '账号',
  idUnique: 'ID唯一',
  loginPassword: '登录密码',
  inviteCode: '内测码',
  inviteOnly: '当前仅开放内测账号注册',
  passwordManaged: '密码由 Supabase Auth 安全保存',
  passwordNotViewable: '已保存的密码不能查看原文。你可以用当前密码修改新密码。',
  changePassword: '修改密码',
  currentPassword: '当前密码',
  newPassword: '新密码',
  confirmPassword: '确认新密码',
  savePassword: '保存密码',
  changingPassword: '修改中...',
  passwordChanged: '密码已修改',
  passwordMismatch: '两次输入的新密码不一致',
  currentPasswordWrong: '当前密码不正确',
  showPassword: '查看密码',
  hidePassword: '隐藏密码',
  accountAccess: '账号访问',
  uploadPhotoLocation: '从照片定位创建星星',
  photoLocationLoading: '正在读取照片定位...',
  photoLocationCreated: '已根据照片创建星星',
  photoLocationNoGps: '找不到该图片的定位信息',
  photoLocationFailed: '无法读取这张照片',
  photoGpsNoteTitle: '照片定位',
  restoreTrackDraft: '发现一条未保存路线草稿，是否恢复？',
  routeGpsWeak: 'GPS 信号弱，正在等待稳定位置',
    loginTitle: '账号登录',
    registerTitle: '账号注册',
    loginHint: '输入已经注册的 ID 和密码登录。',
    registerHint: '第一次使用请注册唯一 ID，之后可在任意设备登录。',
    login: '登录',
    register: '注册',
    loggingIn: '登录中...',
    registering: '创建中...',
    restoringSession: '正在恢复登录...',
    registerPassword: '设置密码',
    registerSuccess: '注册成功，请登录。',
    loginMissing: '请输入账号和密码',
    registerMissing: '请设置账号和密码',
  passwordTooShort: '密码至少需要 6 位',
    loginError: '账号不存在或密码不正确',
    registerError: '无法注册这个账号',
    accountExists: '这个账号已经存在',
    cloudSetupRequired: '云端服务暂时不可用，请稍后再试。',
    cloudConnectivityIssue: '云端连接失败，请检查网络，或用 Safari/Chrome 打开后重试。',
    cloudProjectMismatch: '登录状态异常，请重新登录。',
    cloudConfigInvalid: '云端服务暂时不可用，请稍后再试。',
    cloudEmailConfirmRequired: '请先关闭 Supabase 邮箱确认',
    noImages: '还没有上传过图片',
    openPermissions: '打开权限',
    openPermissionsHint: '请求定位',
    userManual: '用户手册',
    openManual: '打开查阅',
    closeManual: '关闭手册',
    exportData: '导出数据',
    exportJson: '导出阅读版',
    exportingData: '导出中...',
    exportPreparing: '正在准备导出',
    exportImagesProgress: '正在处理图片 {completed}/{total}',
    exportGenerating: '正在生成文件',
    exportImagesMissing: '导出完成，{count} 张图片未嵌入',
    exportDataReady: '阅读版已导出',
    exportDataPartial: '阅读版已导出，部分图片未能写入文件',
    exportDataFailed: '导出失败',
    mcpAccess: '获取MCP',
    mcpGenerateToken: '生成 MCP Token',
    mcpGenerating: '生成中...',
    mcpTokenReady: 'Token 已生成，请现在复制',
    mcpCopyEndpoint: '复制地址',
    mcpCopyHeader: '复制请求头内容',
    mcpCopied: '已复制',
    mcpRevoke: '吊销',
    mcpNoTokens: '暂无可用 MCP Token',
    mcpNameLabel: '名称',
    mcpNameValue: 'My Life Memory',
    mcpTransportLabel: '传输类型',
    mcpTransportValue: 'Streamable HTTP',
    mcpEndpoint: '服务器地址',
    mcpCustomHeader: '自定义请求头',
    mcpHeaderName: 'Authorization',
    mcpHeaderValueHint: '请先生成 Token',
    mcpTokenPrefix: '已生成 Token',
    mcpFailed: 'MCP 服务暂时不可用',
    mcpRevoked: 'Token 已吊销',
    mcpTokenWarning: '完整 Token 只会显示一次。',
    apiSecurity: 'API与安全',
    apiMemoryApiTitle: 'Memory API',
    apiMemoryApiBody: 'Memory API 是 Supabase Edge Function，用于经过认证的外部集成。它读取当前用户自己的记忆数据，需要真实用户 access token。',
    apiMcpSecurityTitle: 'MCP 访问',
    apiMcpSecurityBody: '云端 MCP 也是 Supabase Edge Function。它校验生成的 MCP Token，把 token 映射到唯一用户，并只向 AI 客户端开放只读工具。',
    apiTokenSecurityTitle: 'Token 生成',
    apiTokenSecurityBody: 'MCP Token 在 Supabase 服务端生成，不在前端代码里生成。完整 Token 只显示一次，Supabase 只保存 SHA-256 hash 和短前缀。',
    apiStorageSecurityTitle: '私有媒体',
    apiStorageSecurityBody: '图片文件存放在私有 life-media 桶里，并按用户 ID 分路径。数据库只保存图片路径和元数据，不保存公开图片文件。',
    apiDirectApiTitle: '直接 API 格式',
    apiDirectApiBody: '外部工具调用 memory-api 时，需要 Authorization: Bearer <用户 access token>、apikey: <publishable key>，并传入 search_memories 这类 action。',
    apiNeverExposeTitle: '不要暴露',
    apiNeverExposeBody: '不要把 service_role、内测码、真实 session token、完整 MCP token、数据库连接串写进 app 页面、README 示例、导出文件或截图。',
    searchResultsTitle: '搜索结果',
    searchResultsFor: '关于',
    noSearchResults: '没有匹配的笔记',
    initialPermissionsTitle: '定位权限',
    initialPermissionsBody: '允许定位后，地图会回到你当前的位置，并更新原点。',
    notNow: '稍后',
    manualIntro: 'My life memory 是一个私人生活地图。它从你的当前位置出发，用星星记录重要地点，再把文字、图片、移动路线、坐标和统计放进同一个记忆空间里。',
    manualSections: [
      { title: '地图与星星', body: '星星代表一个地点记忆。你可以点击地图上的空白位置直接创建星星，也可以把星星工具拖到地图上创建；星星放好以后仍然可以拖动调整位置。点开星星后，可以写笔记、添加照片、查看坐标、复制坐标，也可以选择 Apple 地图、高德、百度或 Google 地图打开这个地点。' },
      { title: '定位与方向', body: '打开权限会请求真实 GPS 和手机方向。黑色原点代表你当前的位置，半透明探头表示手机朝向；浏览器和手机支持时，转动手机探头会跟着旋转，走动时位置会随着 GPS 更新。移动端 Safari 通常需要 HTTPS 和用户点击后才能读取方向，室内 GPS 也可能不如室外稳定。' },
      { title: '我的记录', body: '记录来自星星里的笔记，时间以第一次创建为准，后续编辑不会改变创建时间。新建记录会显示在旧记录上方。进入记录详情后可以直接编辑文字和图片，图片下方也可以继续输入文字，改完以后用右侧展开工具里的保存按钮保存。日历只会在有文字、图片或星标的日期下面显示点，也可以取消筛选。' },
      { title: '行程统计', body: '统计页会汇总星星数量、路线距离、常出现地点、排行和点状世界地图。柱状图颜色会跟随星星颜色，方便把统计数据和地图上的记忆对应起来。点状世界地图主要用于整体浏览，它可以打开成更完整的地图视图。' },
      { title: '账号与同步', body: '每个 ID 都是唯一的。第一次使用先注册，注册完成后再用同一个 ID 和密码登录。登录后星星、笔记、路线、主题、个人信息会保存到云端；不同账号即使在同一台设备上切换，也应该只看到各自的数据。' },
    ],
    manualIconsTitle: '常用图标',
    manualIconMap: '地图图标会回到主地图。这里可以查看当前定位、星星、路线，也可以切换地图样式。',
    manualIconStats: '统计图标会进入行程统计页，查看距离、星星数量、常用地点排行和点状世界地图。',
    manualIconRecords: '记录图标会进入我的记录页，按时间查看笔记，也可以用搜索、月份/年份筛选和日历查找。',
    manualIconHome: '主页图标会进入个人区域，用来修改信息、更换主题、查看图片仓库、打开权限、阅读手册或退出账号。',
    manualIconStar: '星星图标用于创建地点记忆。可以点击地图创建，也可以把星星拖到地图上创建；已经放好的星星也可以拖动调整位置，点开后可以编辑笔记和照片。',
    manualIconLocation: '定位图标会让地图回到当前 GPS 原点。原点旁的半透明探头代表手机朝向，权限和设备支持时会随手机转动。',
    manualIconRoute: '路线图标用于开始、暂停、保存或查看自适应移动记录。它用同一套 GPS 过滤逻辑适配步行、骑行、坐车等场景，路线距离会根据 GPS 点计算，GPS 精度越好越准确。室内、电梯、地下空间 GPS 可能漂移；如果想让路线更干净，可以进入前暂停，出来后继续。',
    manualIconCamera: '相机图标用于拍照或给笔记添加图片。移动端浏览器允许时，可以进入更接近全屏的拍摄体验。',
    manualIconPhotoGps: '星星上传图标是星星里的上传箭头，用于读取一张原始照片里的 GPS 信息，并在照片地点自动创建星星和带图笔记。如果照片没有可用定位，只会短暂提示，不会创建星星。',
    manualIconSave: '保存图标用于保存当前笔记修改，包括文字、图片、颜色和字号等内容。',
    manualIconCopy: '复制图标用于复制坐标或相关文字，点击后会出现短暂的复制成功提示。',
    manualIconShare: '打开地图图标用于把地点交给本机地图 App，可选择 Apple 地图、高德、百度或 Google 地图。',
    manualIconSearch: '搜索图标用于搜索笔记文字、地点内容或坐标，方便从大量记录里快速找到目标。',
    permissionRequesting: '正在请求权限...',
    permissionReady: '已请求权限',
    permissionDenied: '无法打开权限，请检查浏览器网站设置',
    permissionUnsupported: '当前浏览器不可用',
    language: '语言',
    exit: '退出账号',
    base: '页面背景',
    card: '内容卡片',
    icon: '图标颜色',
    dark: '选中强调',
    recordsTitle: '我的记录',
    recordsMenu: '记录菜单',
    allRecords: '全部',
    monthlyRecords: '本月',
    annualRecords: '本年',
    noRecords: '还没有笔记记录',
    calendar: '日历',
    closeCalendar: '关闭日历',
    clearDateFilter: '取消筛选',
    previousCalendarPage: '上一页日历',
    nextCalendarPage: '下一页日历',
    weekdays: ['日', '一', '二', '三', '四', '五', '六'],
    search: '搜索',
    searchRecords: '搜索记录',
    searchPlaceholder: '快速搜索地点和文本...',
    runSearch: '执行搜索',
    backToRecords: '返回记录',
    readerMissing: '这条记录已不可用',
    readerEdit: '保存记录',
    readerReadingSize: '调整阅读字号',
    readerUnderline: '添加下划线',
    readerAddPhoto: '添加照片',
    readerJumpImage: '添加图片',
    readerEditColor: '编辑颜色',
    readerCollapseTools: '收起阅读工具',
    readerExpandTools: '展开阅读工具',
    readerLocate: '定位到地图记录',
    removeImage: '移除图片',
    bottomMap: '地图',
    bottomStats: '统计',
    bottomNotes: '记录',
    bottomHome: '主页',
    untitledNote: '未命名笔记',
    noteLabel: '笔记',
    starLabel: '星标',
    addStar: '添加星标',
    noteImageAlt: '笔记图片',
    userFallback: '用户',
    userAvatarAlt: '用户头像',
    currentMapStyleAlt: '当前地图样式',
    aerialMapAlt: '卫星地图',
    darkMapAlt: '深色地图',
    lightMapAlt: '浅色地图',
    closeImagePreview: '关闭图片预览',
    downloadImage: '下载图片',
  },
  ko: {
    modify: '정보 수정',
    theme: '테마 변경',
    gallery: '이미지 갤러리',
    settings: '설정',
    uploadAvatar: '아바타 업로드',
    back: '뒤로',
  userName: '사용자 이름',
  account: '계정',
  idUnique: '고유 ID',
  loginPassword: '로그인 비밀번호',
  inviteCode: '초대 코드',
  inviteOnly: '현재 초대받은 테스트 계정만 가입할 수 있습니다',
  passwordManaged: '비밀번호는 Supabase Auth에서 안전하게 관리됩니다',
  passwordNotViewable: '저장된 비밀번호 원문은 볼 수 없습니다. 현재 비밀번호로 새 비밀번호를 설정할 수 있습니다.',
  changePassword: '비밀번호 변경',
  currentPassword: '현재 비밀번호',
  newPassword: '새 비밀번호',
  confirmPassword: '새 비밀번호 확인',
  savePassword: '비밀번호 저장',
  changingPassword: '변경 중...',
  passwordChanged: '비밀번호를 변경했습니다',
  passwordMismatch: '새 비밀번호가 일치하지 않습니다',
  currentPasswordWrong: '현재 비밀번호가 올바르지 않습니다',
  showPassword: '비밀번호 보기',
  hidePassword: '비밀번호 숨기기',
  accountAccess: '계정 접근',
  uploadPhotoLocation: '사진 GPS로 별표 만들기',
  photoLocationLoading: '사진 위치 읽는 중...',
  photoLocationCreated: '사진 위치로 별표를 만들었습니다',
  photoLocationNoGps: '이 사진에는 사용할 수 있는 GPS가 없습니다',
  photoLocationFailed: '이 사진을 읽을 수 없습니다',
  photoGpsNoteTitle: '사진 위치',
  restoreTrackDraft: '저장하지 않은 경로 임시 기록이 있습니다. 복원할까요?',
  routeGpsWeak: 'GPS 신호가 약해 안정적인 위치를 기다리는 중입니다',
    loginTitle: '계정 로그인',
    registerTitle: '계정 가입',
    loginHint: '등록한 ID와 비밀번호로 로그인하세요.',
    registerHint: '먼저 고유 ID를 만든 뒤 어느 기기에서나 사용하세요.',
    login: '로그인',
    register: '가입',
    loggingIn: '로그인 중...',
    registering: '생성 중...',
    restoringSession: '로그인 상태를 복원하는 중...',
    registerPassword: '비밀번호 설정',
    registerSuccess: '가입이 완료되었습니다. 로그인해 주세요.',
    loginMissing: '계정과 비밀번호를 입력하세요',
    registerMissing: '계정과 비밀번호를 설정하세요',
  passwordTooShort: '비밀번호는 최소 6자여야 합니다',
    loginError: '계정이 없거나 비밀번호가 올바르지 않습니다',
    registerError: '이 계정을 등록할 수 없습니다',
    accountExists: '이미 존재하는 계정입니다',
    cloudSetupRequired: '클라우드 서비스를 잠시 사용할 수 없습니다. 나중에 다시 시도해 주세요.',
    cloudConnectivityIssue: '클라우드 연결에 실패했습니다. 네트워크를 확인하거나 Safari/Chrome에서 다시 열어 주세요.',
    cloudProjectMismatch: '로그인 상태가 올바르지 않습니다. 다시 로그인해 주세요.',
    cloudConfigInvalid: '클라우드 서비스를 잠시 사용할 수 없습니다. 나중에 다시 시도해 주세요.',
    cloudEmailConfirmRequired: '먼저 Supabase 이메일 확인을 꺼주세요',
    noImages: '업로드한 이미지가 없습니다',
    openPermissions: '권한 열기',
    openPermissionsHint: '위치 요청',
    userManual: '사용 설명서',
    openManual: '열어 보기',
    closeManual: '설명서 닫기',
    exportData: '데이터 내보내기',
    exportJson: '읽기용 내보내기',
    exportingData: '내보내는 중...',
    exportPreparing: '내보내기를 준비하는 중',
    exportImagesProgress: '이미지 처리 중 {completed}/{total}',
    exportGenerating: '파일 생성 중',
    exportImagesMissing: '내보내기 완료. 이미지 {count}장을 포함하지 못했습니다.',
    exportDataReady: '읽기용 파일을 내보냈습니다',
    exportDataPartial: '읽기용 파일을 내보냈습니다. 일부 이미지는 포함하지 못했습니다.',
    exportDataFailed: '데이터를 내보내지 못했습니다',
    mcpAccess: 'MCP 받기',
    mcpGenerateToken: 'MCP 토큰 생성',
    mcpGenerating: '생성 중...',
    mcpTokenReady: '토큰이 생성되었습니다. 지금 복사하세요.',
    mcpCopyEndpoint: '주소 복사',
    mcpCopyHeader: '헤더 값 복사',
    mcpCopied: '복사됨',
    mcpRevoke: '해지',
    mcpNoTokens: '활성 MCP 토큰 없음',
    mcpNameLabel: '이름',
    mcpNameValue: 'My Life Memory',
    mcpTransportLabel: '전송 방식',
    mcpTransportValue: 'Streamable HTTP',
    mcpEndpoint: '서버 주소',
    mcpCustomHeader: '사용자 지정 요청 헤더',
    mcpHeaderName: 'Authorization',
    mcpHeaderValueHint: '먼저 토큰을 생성하세요',
    mcpTokenPrefix: '생성된 토큰',
    mcpFailed: 'MCP 서비스를 사용할 수 없습니다',
    mcpRevoked: '토큰을 해지했습니다',
    mcpTokenWarning: '전체 토큰은 한 번만 표시됩니다.',
    apiSecurity: 'API와 보안',
    apiMemoryApiTitle: 'Memory API',
    apiMemoryApiBody: 'Memory API는 인증된 외부 연동을 위한 Supabase Edge Function입니다. 현재 사용자 기억 데이터만 읽으며 실제 사용자 access token이 필요합니다.',
    apiMcpSecurityTitle: 'MCP 접근',
    apiMcpSecurityBody: '클라우드 MCP도 Supabase Edge Function입니다. 생성된 MCP 토큰을 검증해 한 사용자와 연결하고 AI 클라이언트에는 읽기 전용 도구만 제공합니다.',
    apiTokenSecurityTitle: '토큰 생성',
    apiTokenSecurityBody: 'MCP 토큰은 프론트엔드가 아니라 Supabase 서버에서 생성됩니다. 전체 토큰은 한 번만 표시되고, Supabase에는 SHA-256 해시와 짧은 접두사만 저장됩니다.',
    apiStorageSecurityTitle: '비공개 미디어',
    apiStorageSecurityBody: '이미지는 비공개 life-media 버킷에 사용자 ID별 경로로 저장됩니다. 데이터베이스에는 경로와 메타데이터만 저장됩니다.',
    apiDirectApiTitle: '직접 API 형식',
    apiDirectApiBody: '외부 도구는 memory-api에 Authorization: Bearer <user access token>, apikey: <publishable key>, search_memories 같은 action을 담아 POST해야 합니다.',
    apiNeverExposeTitle: '노출 금지',
    apiNeverExposeBody: 'service_role, 초대 코드, 실제 session token, 원본 MCP token, 데이터베이스 연결 문자열을 앱 화면, README 예시, 내보내기 파일, 스크린샷에 넣지 마세요.',
    searchResultsTitle: '검색 결과',
    searchResultsFor: '검색어',
    noSearchResults: '일치하는 노트가 없습니다',
    initialPermissionsTitle: '위치 권한',
    initialPermissionsBody: '위치를 허용하면 지도가 현재 위치로 이동하고 원점이 업데이트됩니다.',
    notNow: '나중에',
    manualIntro: 'My life memory는 현재 위치에서 시작해 별표로 중요한 장소를 남기고, 글, 사진, 이동 경로, 좌표, 통계를 하나의 개인 기억 지도에 연결하는 앱입니다.',
    manualSections: [
      { title: '지도와 별표', body: '별표는 하나의 장소 기억입니다. 지도 빈 곳을 탭해 바로 만들 수 있고, 별표 도구를 지도 위로 끌어 더 정확히 만들 수도 있습니다. 만든 뒤에도 별표를 끌어 위치를 조정할 수 있습니다. 별표를 열면 노트 작성, 사진 추가, 좌표 보기, 좌표 복사, 다른 지도 앱에서 열기를 할 수 있습니다.' },
      { title: '위치와 방향', body: '권한을 열면 실제 GPS와 휴대폰 방향을 요청합니다. 검은 원점은 현재 위치이고 반투명 표시는 휴대폰이 향하는 방향입니다. 모바일 Safari에서는 보통 HTTPS와 사용자 탭이 필요하며, 실내보다 실외 GPS가 더 안정적입니다.' },
      { title: '기록', body: '기록은 별표 안의 노트에서 만들어지며 처음 만든 시간이 기준입니다. 새 기록은 오래된 기록보다 위에 표시됩니다. 상세 화면에서 텍스트와 이미지를 바로 편집하고, 펼쳐진 도구의 저장 버튼으로 변경 사항을 저장합니다. 캘린더는 내용이나 별표가 있는 날짜에만 점을 표시합니다.' },
      { title: '통계', body: '통계 화면은 별표 수, 이동 거리, 자주 남긴 장소, 순위, 점 형태의 세계 지도를 요약합니다. 막대 색상은 별표 색상을 따라 지도 기억과 통계가 이어져 보이게 합니다.' },
      { title: '계정과 동기화', body: '각 ID는 고유합니다. 처음에는 가입하고, 가입 후 같은 ID와 비밀번호로 로그인합니다. 로그인하면 별표, 노트, 경로, 테마, 프로필이 클라우드에 저장되며 같은 기기에서 계정을 바꿔도 각자의 데이터만 보여야 합니다.' },
    ],
    manualIconsTitle: '주요 아이콘',
    manualIconMap: '지도 아이콘은 현재 위치, 별표, 경로, 지도 스타일을 보는 기본 지도로 돌아갑니다.',
    manualIconStats: '통계 아이콘은 거리, 별표 수, 자주 남긴 장소 순위, 점 형태의 세계 지도 요약을 엽니다.',
    manualIconRecords: '기록 아이콘은 저장된 노트를 시간순으로 보여주며 검색, 기간 필터, 캘린더를 사용할 수 있습니다.',
    manualIconHome: '홈 아이콘은 프로필, 테마, 이미지 갤러리, 권한, 사용 설명서, 로그아웃을 여는 개인 영역입니다.',
    manualIconStar: '별표 아이콘은 장소 기억을 만듭니다. 지도를 탭하거나 별표를 끌어 만들 수 있고, 만든 별표도 끌어서 위치를 조정할 수 있습니다.',
    manualIconLocation: '위치 아이콘은 지도를 현재 GPS 원점으로 되돌립니다. 방향 표시는 권한과 기기가 지원할 때 휴대폰 방향에 맞춰 회전합니다.',
    manualIconRoute: '경로 아이콘은 적응형 이동 기록을 시작, 일시정지, 저장, 확인할 때 사용합니다. 걷기, 자전거, 차량, 대중교통을 하나의 GPS 필터로 처리하며 거리는 GPS 포인트를 기준으로 계산됩니다. 실내, 엘리베이터, 지하 공간에서는 GPS가 흔들릴 수 있으니 더 깔끔한 경로를 원하면 들어가기 전에 일시정지하고 나온 뒤 다시 이어가세요.',
    manualIconCamera: '카메라 아이콘은 사진을 촬영하거나 노트에 이미지를 추가합니다. 모바일 브라우저가 허용하면 더 큰 촬영 화면을 사용할 수 있습니다.',
    manualIconPhotoGps: '별표 안의 업로드 화살표 아이콘은 원본 사진의 GPS를 읽어 해당 위치에 사진 노트가 포함된 별표를 만듭니다. 사용할 수 있는 위치 정보가 없으면 짧게 알림만 표시하고 별표는 만들지 않습니다.',
    manualIconSave: '저장 아이콘은 현재 노트의 텍스트, 이미지, 색상, 글자 크기 변경을 저장합니다.',
    manualIconCopy: '복사 아이콘은 좌표나 관련 텍스트를 클립보드에 복사하고 짧은 완료 메시지를 보여줍니다.',
    manualIconShare: '지도 열기 아이콘은 장소를 Apple 지도, AMap, Baidu, Google 지도 등 지원되는 앱으로 엽니다.',
    manualIconSearch: '검색 아이콘은 노트 내용, 장소 텍스트, 좌표를 빠르게 찾는 데 사용합니다.',
    permissionRequesting: '권한 요청 중...',
    permissionReady: '권한을 요청했습니다',
    permissionDenied: '권한을 열 수 없습니다. 브라우저 사이트 설정을 확인하세요.',
    permissionUnsupported: '이 브라우저에서는 권한을 사용할 수 없습니다',
    language: '언어',
    exit: '로그아웃',
    base: '화면 배경',
    card: '카드/패널',
    icon: '버튼/아이콘',
    dark: '선택 강조',
    recordsTitle: '내 기록',
    recordsMenu: '기록 메뉴',
    allRecords: '전체',
    monthlyRecords: '이번 달',
    annualRecords: '올해',
    noRecords: '아직 노트 기록이 없습니다',
    calendar: '캘린더',
    closeCalendar: '캘린더 닫기',
    clearDateFilter: '필터 해제',
    previousCalendarPage: '이전 캘린더 페이지',
    nextCalendarPage: '다음 캘린더 페이지',
    weekdays: ['일', '월', '화', '수', '목', '금', '토'],
    search: '검색',
    searchRecords: '기록 검색',
    searchPlaceholder: '장소와 텍스트를 빠르게 검색...',
    runSearch: '검색 실행',
    backToRecords: '기록으로 돌아가기',
    readerMissing: '이 기록은 더 이상 사용할 수 없습니다',
    readerEdit: '기록 저장',
    readerReadingSize: '읽기 글자 크기 변경',
    readerUnderline: '밑줄',
    readerAddPhoto: '사진 추가',
    readerJumpImage: '이미지 추가',
    readerEditColor: '색상 편집',
    readerCollapseTools: '읽기 도구 접기',
    readerExpandTools: '읽기 도구 펼치기',
    readerLocate: '지도에서 기록 위치 찾기',
    removeImage: '이미지 제거',
    bottomMap: '지도',
    bottomStats: '통계',
    bottomNotes: '기록',
    bottomHome: '홈',
    untitledNote: '제목 없는 노트',
    noteLabel: '노트',
    starLabel: '별표',
    addStar: '별표 추가',
    noteImageAlt: '노트 이미지',
    userFallback: '사용자',
    userAvatarAlt: '사용자 아바타',
    currentMapStyleAlt: '현재 지도 스타일',
    aerialMapAlt: '위성 지도',
    darkMapAlt: '어두운 지도',
    lightMapAlt: '밝은 지도',
    closeImagePreview: '이미지 미리보기 닫기',
    downloadImage: '이미지 다운로드',
  },
};
